theme: jekyll-theme-cayman
title: javafuns@github.io
description: Code snippet, doc, notes, etc. 
logo: 
disqus_shortname:
markdown:
timezone:
collections:
  pages:
    layout: default
    output: true
    permalink: /:collection/:path
