theme: jekyll-theme-cayman
title: Go with Java and Python
description: Code snippet, doc, notes, etc. 
logo: 
disqus_shortname:
markdown:
timezone:

# Listing all of categories of Pages (not for Posts)
page-categories: [linux, git, javascript, python, microservice, docker, kubernetes]

paginate: 10
paginate_path: "blog/page:num/"

# Featured Tags
featured-tags: true
featured-condition-size: 1

collections:
  pages:
    layout: page
    output: true
    permalink: /:collection/:path

defaults:
  -
    scope:
      path: ""
    values:
      author: "Gavin Zhang"
      layout: "default"
      #permalink: /:title
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      permalink: /blog/:categories/:year/:month/:day/:title
  -
    scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "page"
