theme: jekyll-theme-cayman
title: javafuns@github.io
description: Code snippet, doc, notes, etc. 
logo: 
disqus_shortname:
markdown:
timezone:

collections:
  #posts:
  #  layout: post
  #  output: true
  #  permalink: /:collection/:path
  pages:
    layout: default
    output: true
    permalink: /:collection/:path

defaults:
  -
    scope:
      path: ""
    values:
      author: "Gavin Zhang"
      layout: "default"
      #permalink: /:title
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      permalink: /posts/:categories/:year/:month/:day/:title
  -
    scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "default"
