theme: jekyll-theme-cayman
title: Go with Java and Python
description: Code snippet, doc, notes, etc. 
logo: 
disqus_shortname:
markdown:
timezone:

paginate: 10
paginate_path: "blog/page:num/"

# Featured Tags
featured-tags: true
featured-condition-size: 1

collections:
  blog:
    layout: post
    output: true
  pages:
    layout: default
    output: true
    permalink: /:collection/:path

defaults:
  -
    scope:
      path: ""
    values:
      author: "Gavin Zhang"
      layout: "default"
      #permalink: /:title
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      permalink: /blog/:categories/:year/:month/:day/:title
  -
    scope:
      path: "blog"
      type: "posts"
    values:
      layout: "post"
      permalink: /:collection/:categories/:year/:month/:day/:title
  -
    scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "default"
